# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0 # Use a specific version (latest stable recommended)
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
        args: ['--maxkb=2000'] # Adjust max file size as needed for datasets/models
      - id: mixed-line-ending
      - id: detect-private-key
      - id: check-merge-conflict

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.5.0' # Should match your ruff version in pyproject.toml
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix] # Auto-fix basic issues, exit if more fixes needed
      - id: ruff-format # Use ruff's formatter